name: shared
description: A new Flutter package.
version: 0.0.1
author: ToanDev
homepage: ToanDev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.10
  flutter_spinkit: ^4.1.2+1
  synchronized: ^2.2.0+2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

